INSERT INTO `etapa` (`id_etapa`, `nombre_etapa`, `peso_etapa`, `descripcion_etapa`, `id_tipologia`, `estado`) VALUES
(1, 'ITCP', 10, 'Etapa de proyecto', 5, 'false'),
(2, 'EDTP', 30, 'Etapa de proyecto', 5, 'true'),
(3, 'Gestión Financiamiento', 20, 'Etapa de proyecto', 5, 'true'),
(4, 'Ejecución', 50, 'Etapa de proyecto', 5, 'true'),
(5, 'Propuesta', 30, 'Etapa de normativa', 2, 'true'),
(6, 'Validación ', 30, 'Etapa de normativa', 2, 'true'),
(7, 'Promulgación', 40, 'Etapa de normativa', 2, 'true'),
(8, 'Propuesta', 30, 'Etapa de Plan/estrategia', 3, 'true'),
(9, 'Validación', 30, 'Etapa de Plan/estrategia', 3, 'true'),
(10, 'Aprobación ', 40, 'Etapa de Plan/estrategia', 3, 'true'),
(11, 'Organización', 30, 'Etapa de Actividad', 1, 'true'),
(12, 'Ejecución', 70, 'Etapa de Actividad', 1, 'true'),
(13, 'EDTP', 30, 'Etapa de Programa', 4, 'true'),
(14, 'Gestión Financiamiento', 20, 'Etapa de Programa', 4, 'true'),
(15, 'Ejecución', 50, 'Etapa de Programa', 4, 'true');